/*
	Copyright (C) 2026  Orsiris de Jong <ozy@netpower.fr>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

package main

import (
	"fmt"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"vmsync/pkg/restorepoint"
)

// Operation is a one-shot instruction for exactly one agent.
//
// Deliberately NOT part of the schedule. The schedule is desired state:
// re-delivering it is idempotent and harmless, which is what lets an agent
// keep running it through a partition. A promotion is an event -- delivering
// it twice must not promote twice -- so it travels on its own channel with
// its own identity and its own durable record of having been acted on.
type Operation struct {
	// ID is the idempotency key, generated by the UI. Everything about
	// replay protection hangs off it.
	ID   string `json:"id"`
	Kind string `json:"kind"`
	VM   string `json:"vm"`
	// PeerHost and PeerVM are what the UI BELIEVES the other end of the pair
	// is. They are checked against what this host's own libvirt metadata
	// says and the operation is refused on a mismatch -- never used as the
	// endpoint directly.
	//
	// That direction is the whole point. Everywhere else in this agent the
	// endpoints come from the VM's own replica_source/replica_targets, on
	// the reasoning that a name read from local state is not
	// attacker-controlled while one arriving over the network is a
	// parameter needing validation. Promotion is the one path that can stop
	// a production VM, so it is the last place to relax that.
	PeerHost string `json:"peer_host,omitempty"`
	PeerVM   string `json:"peer_vm,omitempty"`
	// Mode is "planned" or "forced" for a promotion.
	Mode string `json:"mode,omitempty"`
	// StartVM boots the domain once the promotion is recorded.
	StartVM bool `json:"start_vm,omitempty"`
	// Force bypasses the replica-corroboration checks (never the role
	// checks), making the reported data-loss window unknown rather than
	// fabricated.
	Force bool `json:"force,omitempty"`
	// ArmFence asks a promotion to authorise shutting the displaced source
	// down, so the same VM does not end up serving in two places.
	//
	// Opt-in, and it stays opt-in all the way from the UI: a DR drill is a
	// promotion too, and a drill that stopped production would be a far
	// worse failure than the split brain it was rehearsing for. The source
	// to fence is NOT taken from this message -- vmsync resolves it from the
	// promoted domain's own replica_source, for the same reason PeerHost
	// above is a claim to be checked rather than an endpoint to use.
	ArmFence bool `json:"arm_fence,omitempty"`
	// ShutdownTimeoutSec is how long a clean guest shutdown may take, already
	// resolved by the UI from the VM's own setting or the estate default.
	//
	// Carried on the operation rather than looked up when it runs, so the
	// instruction means the same thing whenever it is executed -- a decision
	// that silently meant 300 seconds in March and 900 in April is not one
	// anybody can audit.
	ShutdownTimeoutSec int `json:"shutdown_timeout_sec,omitempty"`
	// Tag names the restore point a restore operation puts back.
	//
	// The one operation parameter that cannot be checked against local
	// libvirt metadata the way PeerHost is, because a restore point is a
	// directory rather than anything a domain records. It is checked against
	// the filesystem instead: vmsync confirms the tag is in the target's own
	// listing before it writes anything, and restorepoint.ParseTag refuses
	// path separators, shell metacharacters and parent references outright,
	// because this value is interpolated into commands including rm -rf.
	//
	// The agent still rejects an unknown tag before running anything, so a
	// stale one from a UI whose report predates a prune is REFUSED and
	// reported rather than surfacing as a failed run whose output nobody
	// reads.
	Tag string `json:"tag,omitempty"`

	CreatedAtUnix int64  `json:"created_at_unix"`
	CreatedBy     string `json:"created_by,omitempty"`
	// NotAfterUnix is a hard deadline, set by the UI. Past it, the agent
	// refuses and reports the refusal.
	//
	// Without this an operation is armed forever: a target host that was
	// down when a forced promote was issued would execute it whenever it
	// eventually came back -- hours or days later, as a FIRST delivery that
	// no replay guard covers -- long after the incident that motivated it
	// was resolved. That is not a retry, it is an unattended failover
	// nobody currently wants.
	NotAfterUnix int64 `json:"not_after_unix,omitempty"`
}

// Operation kinds.
const (
	OpPromote  = "promote"
	OpInvert   = "invert"
	OpShutdown = "shutdown-domain"
	OpSetRole  = "set-role"
	OpReinit   = "reinit"
	// OpForceClean is a reinit for a target that an ordinary reinit cannot
	// get past: it undefines the target domain, overrides the promoted and
	// paused role interlocks, and clears a shut-down source's checkpoint
	// chain including its bitmaps. Like OpReinit it runs on the SOURCE's
	// agent, because it is a sync.
	//
	// Separate from OpReinit rather than a flag on it so that the audit
	// trail names what actually happened: these two destroy different
	// amounts of the target, and after the fact "reinit" would not say
	// which one ran.
	OpForceClean = "force-clean"
	// OpRestore rolls a replica back to one of its restore points, in place.
	//
	// The most destructive operation here: it replaces the replica's disks
	// and pauses replication into it. It runs on the host holding the disks,
	// with a local URI and no credentials, exactly like promote and
	// shutdown-domain.
	OpRestore = "restore"
)

// OperationResult is what the agent reports back.
type OperationResult struct {
	ID             string `json:"id"`
	Kind           string `json:"kind"`
	VM             string `json:"vm"`
	State          string `json:"state"`
	StartedAtUnix  int64  `json:"started_at_unix,omitempty"`
	FinishedAtUnix int64  `json:"finished_at_unix,omitempty"`
	ExitCode       int    `json:"exit_code,omitempty"`
	Error          string `json:"error,omitempty"`
	LogTail        string `json:"log_tail,omitempty"`
}

// Terminal and non-terminal states an operation can be recorded in.
const (
	// OpStateRunning is written BEFORE the work starts. A ledger entry left
	// in this state across a restart means the agent died mid-operation.
	OpStateRunning = "running"
	OpStateDone    = "done"
	OpStateFailed  = "failed"
	// OpStateExpired is a refusal to act on an instruction that is no longer
	// current. Reported like any other outcome so the audit entry closes
	// rather than hanging as "pending" forever.
	OpStateExpired = "expired"
	// OpStateRefused covers a precondition the agent itself rejected -- a
	// peer that does not match local metadata, an unknown VM, an unknown
	// kind from a newer UI.
	OpStateRefused = "refused"
	// OpStateUnknown is what a `running` entry becomes when it is found
	// after a restart. It is NEVER retried: something was part-way done to a
	// domain and only a person can safely say what state it reached.
	OpStateUnknown = "unknown"
)

// ledgerEntry is one operation's durable record.
type ledgerEntry struct {
	ID     string          `json:"id"`
	Kind   string          `json:"kind"`
	VM     string          `json:"vm"`
	State  string          `json:"state"`
	AtUnix int64           `json:"at_unix"`
	Result OperationResult `json:"result"`
}

// operationLedger is the agent's durable memory of what it has been asked to
// do, and what came of it.
//
// Two properties matter, and they are the ones a naive "remember completed
// IDs" set does not have:
//
//   - Intent is recorded BEFORE the work starts, not after. Recording
//     completion afterwards leaves a window -- the entire duration of a
//     graceful shutdown, say -- in which a crash loses all trace of an
//     operation that was half performed, and the cached config would replay
//     it on restart. That is the automatic re-execution of a partially
//     completed failover, which is the one thing this design forbids.
//
//   - The RESULT is kept, not just the fact of completion. If the report
//     carrying it never lands, the UI keeps publishing the operation and the
//     agent keeps seeing it; without the stored result it would skip
//     silently forever while the UI waited forever. Keeping it lets the
//     agent re-attach the same answer to every report until the operation
//     stops being published -- acknowledgement by repetition, needing no new
//     endpoint and no extra state on either side.
type operationLedger struct {
	path string

	mu      sync.Mutex
	entries map[string]ledgerEntry
}

func newOperationLedger(stateDir string) *operationLedger {
	return &operationLedger{
		path:    filepath.Join(stateDir, "operations.json"),
		entries: map[string]ledgerEntry{},
	}
}

// Load reads the ledger, promoting anything left `running` to `unknown`.
//
// A `running` entry can only mean the agent died between starting an
// operation and finishing it. It is never resumed and never retried: a
// half-completed promotion or inversion left a domain in a state only an
// inspection can establish, and guessing wrong in either direction is worse
// than reporting honestly that a person needs to look.
func (l *operationLedger) Load() error {
	var entries map[string]ledgerEntry
	ok, err := readJSON(l.path, &entries)
	if err != nil {
		return err
	}
	l.mu.Lock()
	defer l.mu.Unlock()
	if !ok || entries == nil {
		l.entries = map[string]ledgerEntry{}
		return nil
	}
	for id, e := range entries {
		if e.State == OpStateRunning {
			e.State = OpStateUnknown
			e.Result.State = OpStateUnknown
			e.Result.Error = "the agent stopped while this operation was in progress; its outcome was never established and it will not be retried automatically"
			entries[id] = e
		}
	}
	l.entries = entries
	return nil
}

// Seen reports whether this ID has a record in ANY state, along with the
// result to re-report.
//
// Any state at all is a refusal to act again -- including `failed`. A failed
// operation is not retried on its own: re-running a failover that already
// went wrong once, unattended, is how a bad situation is compounded. A
// person re-issues it with a fresh ID once they know why.
func (l *operationLedger) Seen(id string) (OperationResult, bool) {
	l.mu.Lock()
	defer l.mu.Unlock()
	e, ok := l.entries[id]
	return e.Result, ok
}

// Begin records intent and persists it before any work happens.
func (l *operationLedger) Begin(op Operation, now time.Time) error {
	return l.put(ledgerEntry{
		ID: op.ID, Kind: op.Kind, VM: op.VM, State: OpStateRunning, AtUnix: now.Unix(),
		Result: OperationResult{
			ID: op.ID, Kind: op.Kind, VM: op.VM,
			State: OpStateRunning, StartedAtUnix: now.Unix(),
		},
	})
}

// Finish records a terminal outcome.
func (l *operationLedger) Finish(op Operation, res OperationResult, now time.Time) error {
	res.ID, res.Kind, res.VM = op.ID, op.Kind, op.VM
	res.FinishedAtUnix = now.Unix()
	return l.put(ledgerEntry{
		ID: op.ID, Kind: op.Kind, VM: op.VM, State: res.State, AtUnix: now.Unix(), Result: res,
	})
}

// Abandon undoes a Begin, so the operation is retried on a later tick.
//
// This is the one hole in "recorded once, never retried", and it is deliberate
// and narrow. That rule exists because a crash mid-operation is
// indistinguishable from a completed one -- so intent is written first and a
// `running` record that survives a restart is never re-run, on the reasoning
// that replaying a failover is worse than not finishing one.
//
// Contention is the case where that reasoning does not apply: vmsync exited
// cleanly and deliberately, with a code that means "I took no lock and did
// nothing". That is a positive statement from the process itself, not an
// absence of information, and it is the only thing this is called for. An
// operation stuck behind a sync would otherwise burn its id forever and have
// to be reissued by hand from the UI -- while the reason it failed cleared up
// on its own seconds later.
//
// Removing the entry rather than marking it: Seen() reports any recorded id as
// seen whatever its state, and Results() reports every entry to the UI. A
// record left behind would be both un-retryable and visible as an outcome that
// never happened.
func (l *operationLedger) Abandon(id string) error {
	l.mu.Lock()
	if _, ok := l.entries[id]; !ok {
		l.mu.Unlock()
		return nil
	}
	delete(l.entries, id)
	snapshot := make(map[string]ledgerEntry, len(l.entries))
	for k, v := range l.entries {
		snapshot[k] = v
	}
	l.mu.Unlock()

	if err := writeJSONAtomic(l.path, snapshot, 0o644); err != nil {
		return fmt.Errorf("remove the abandoned record of operation %s from the ledger: %w", id, err)
	}
	return nil
}

func (l *operationLedger) put(e ledgerEntry) error {
	l.mu.Lock()
	l.entries[e.ID] = e
	snapshot := make(map[string]ledgerEntry, len(l.entries))
	for k, v := range l.entries {
		snapshot[k] = v
	}
	l.mu.Unlock()

	// 0644 and atomic, like the config cache: it holds no secret, and the
	// rename is what stops a crash mid-write from replacing the record of an
	// in-progress operation with a truncated file.
	if err := writeJSONAtomic(l.path, snapshot, 0o644); err != nil {
		return fmt.Errorf("record operation %s in the ledger: %w", e.ID, err)
	}
	return nil
}

// Results returns every stored result, for attaching to a report.
func (l *operationLedger) Results() []OperationResult {
	l.mu.Lock()
	defer l.mu.Unlock()
	out := make([]OperationResult, 0, len(l.entries))
	for _, e := range l.entries {
		if e.Result.ID != "" {
			out = append(out, e.Result)
		}
	}
	return out
}

// Forget drops records for operations the UI has stopped publishing.
//
// The UI removing an operation IS the acknowledgement, so this is where the
// ledger is bounded: without it, a long-lived agent accumulates a record per
// failover forever. Anything still published is kept, however old.
func (l *operationLedger) Forget(stillPublished map[string]bool) {
	l.mu.Lock()
	var drop []string
	for id := range l.entries {
		if !stillPublished[id] {
			drop = append(drop, id)
		}
	}
	for _, id := range drop {
		delete(l.entries, id)
	}
	snapshot := make(map[string]ledgerEntry, len(l.entries))
	for k, v := range l.entries {
		snapshot[k] = v
	}
	l.mu.Unlock()

	if len(drop) == 0 {
		return
	}
	// Best-effort: a failure here costs a re-report of something already
	// acknowledged, which is harmless, so it must not fail the caller.
	_ = writeJSONAtomic(l.path, snapshot, 0o644)
}

// Validate checks an operation before anything is done with it.
//
// localPeers is every "host:domain" this VM's OWN libvirt metadata records
// as a replication peer -- its replica_source if it is a target, and every
// entry of replica_targets if it is a source. Empty means the domain
// records no replication relationship at all.
//
// A set rather than a single value because a source legitimately fans out
// to several targets, and any one of them is a peer this host would
// recognise. Reducing that to one would mean either picking arbitrarily or
// refusing a perfectly ordinary topology.
func (op Operation) Validate(localPeers []string, now time.Time) error {
	if op.ID == "" {
		return fmt.Errorf("operation has no id")
	}
	if op.VM == "" {
		return fmt.Errorf("operation %s names no vm", op.ID)
	}
	switch op.Kind {
	case OpPromote, OpInvert, OpShutdown, OpSetRole, OpReinit, OpForceClean:
	case OpRestore:
		// Checked HERE rather than in operationArgs, because a kind that
		// passes Validate and then fails argv-building is recorded refused
		// with its ID burned forever -- a bad tag would cost the operator
		// the operation, not just the attempt. ParseTag is also what bounds
		// the value before it reaches a shell: it refuses path separators,
		// shell metacharacters and parent references, and this string ends
		// up interpolated into commands including rm -rf.
		if op.Tag == "" {
			return fmt.Errorf("operation %s is a restore but names no restore point", op.ID)
		}
		if _, err := restorepoint.ParseTag(op.Tag); err != nil {
			return fmt.Errorf("operation %s names an unusable restore point: %w", op.ID, err)
		}
	default:
		// A kind from a newer UI. Refused and REPORTED rather than ignored:
		// silence here would leave an operator watching a failover sit
		// pending against a healthy agent with nothing saying why.
		return fmt.Errorf("operation %s has kind %q, which this agent does not understand -- it is probably newer than this agent", op.ID, op.Kind)
	}
	if op.NotAfterUnix > 0 && now.Unix() > op.NotAfterUnix {
		return fmt.Errorf("operation %s expired at %s and will not be executed", op.ID, time.Unix(op.NotAfterUnix, 0).Format(time.RFC3339))
	}
	if op.PeerHost != "" {
		want := op.PeerHost + ":" + op.PeerVM
		if op.PeerVM == "" {
			want = op.PeerHost + ":" + op.VM
		}
		if len(localPeers) == 0 {
			return fmt.Errorf("operation %s names peer %s, but %s records no replication peer of its own", op.ID, want, op.VM)
		}
		found := false
		for _, p := range localPeers {
			if equalFoldRef(p, want) {
				found = true
				break
			}
		}
		if !found {
			return fmt.Errorf("operation %s names peer %s, but %s's own metadata records %s -- refusing to act on a pair this host does not recognise",
				op.ID, want, op.VM, strings.Join(localPeers, ", "))
		}
	}
	return nil
}

// equalFoldRef compares two "host:domain" references, case-insensitively on
// the host, exactly as pickTarget already does when matching a schedule
// entry's target host against a VM's replica_targets.
func equalFoldRef(a, b string) bool {
	ah, ad := splitReplicaRef(a)
	bh, bd := splitReplicaRef(b)
	return strings.EqualFold(ah, bh) && ad == bd
}
